# Generated by Django 3.2.6 on 2021-09-07 04:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 4, 44, 28, 267152, tzinfo=utc), verbose_name='end date'),
            preserve_default=False,
        ),
    ]
